<section class ="MainContent">
    <div class="MainContent-ArticlePicture">
        <img src="" alt="" class="ArticlePicture-articleimg">
        <img src="" alt="" class="ArticlePicture-articleimg">
        <img src="" alt="" class="ArticlePicture-articleimg">
        <img src="" alt="" class="ArticlePicture-articleimg">
        <img src="" alt="" class="ArticlePicture-articleimg">
    </div>
    
    <div class="MainContent-ArticleInfo">
       <h2 class="ArticleInfo-titreArticle">Titre</h2>
       <p class="ArticleInfo-prixArticle"></p>
    </div>
    <div class="ArticleInfo-coulArticle">
        <h2 class="ArticleInfo-coulArticle-titre">Couleur</h2>
        <img src="" alt="" class="coulVignet">
        <img src="" alt="" class="coulVignet">
        <img src="" alt="" class="coulVignet">
        <img src="" alt="" class="coulVignet">
        <img src="" alt="" class="coulVignet">
    </div>
    <div class="ArticleInfo-taiArticle">
        <h2 class="ArticleInfo-taiArticle">Taille</h2>
        <img src="" alt="" class="taiVignet">
        <img src="" alt="" class="taiVignet">
        <img src="" alt="" class="taiVignet">
        <img src="" alt="" class="taiVignet">
        <img src="" alt="" class="taiVignet">
    </div>
    <button class ='addButton'></button>
    <div>
        <h2 class="ArticleInfo-detailsTitre">Details</h2>
        <p class="detailsContent"></p>
    </div>

</section>