<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
</head>
<body>
<header class = 'siteHeader'>
    <section class =''>
        <img src="" alt="" >
        <h1>SundayMorning</h1>
        <nav>
        </nav>
    </section>
    <section>
        <img src="" alt="">
        <nav>
            <a href=""></a>
            <a href=""></a>
            <a href=""></a>   
        </nav>
        <img src="" alt="">
        <img src="" alt="">
    </section>   
</header>
<main>
    <?php include TEMPLATE_DIR . '/' . $template . '.phtml';?>
</main>
<aside>
    
</aside>
    
</body>
</html>