<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
</head>
<body>
<header>
    <section>
        <img src="" alt="" >
        <h1>SundayMorning</h1>
        <nav>
           
        </nav>
    </section>
    <section>
        <img src="" alt="">
        <nav>
            <a href=""></a>
            <a href=""></a>
            <a href=""></a>   
        </nav>
        <img src="" alt="">
        <img src="" alt="">
    </section>   
</header>
<main>
    <h2><?=$data['Article']['nom_article']?></h2>
    <h3><?=$data['Categorie']['lib_categorie']?></h3>
    <p><?=$data['Marque']['lib_marque']?></p>
    <p><?=$data['Couleur']['nom_couleur']?></p>
    <p><?=$data['Taille']['lib_taille']?></p>
</main>
<aside>
    
</aside>
    
</body>
</html>